version: '3.8'

services:
  ai-tool:
    build: .
    container_name: ai-tool-service
    ports:
      - "50051:50051"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 50051), timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 